from __future__ import annotations

import numpy as np


BODY_POSE_BODY_FBX_LOCAL_DELTA_KEY = "body_pose_body_fbx_local_delta_6d"

TASK_MODE_REALTIME_POSE = "realtime_pose_reconstruction"
TASK_MODES = (TASK_MODE_REALTIME_POSE,)

# region 时间契约

REALTIME_POSE_FPS = 30.0
REALTIME_POSE_HISTORY_LENGTH = 10
REALTIME_POSE_HISTORY_FRAME_OFFSETS = tuple(range(-10, 0))
REALTIME_POSE_HISTORY_ANCHOR_INDICES = tuple(range(10))
REALTIME_POSE_HISTORY_ANCHOR_COUNT = REALTIME_POSE_HISTORY_LENGTH

# 单帧 DiT 只扩散当前帧；未来 10 帧完全由 Predictor 作为条件提供。
REALTIME_POSE_TARGET_START = REALTIME_POSE_HISTORY_LENGTH
REALTIME_POSE_TARGET_LENGTH = 1
REALTIME_POSE_TARGET_FRAME_OFFSETS = (0,)

PREDICTOR_CORE_TRACKER_PREVIOUS_OFFSET = -11
PREDICTOR_CORE_TRACKER_FRAME_OFFSETS = tuple(range(-10, 1))
PREDICTOR_CORE_TRACKER_CONTEXT_LENGTH = len(PREDICTOR_CORE_TRACKER_FRAME_OFFSETS)
PREDICTOR_FUTURE_FRAME_COUNT = 10
PREDICTOR_POSE_HORIZON_LENGTH = PREDICTOR_FUTURE_FRAME_COUNT + 1
PREDICTOR_POSE_HORIZON_FRAME_OFFSETS = tuple(
    range(PREDICTOR_POSE_HORIZON_LENGTH)
)
PREDICTOR_FREE_RUNNING_MAX_STEPS = 30
PREDICTOR_TRAINING_LAST_OFFSET = (
    PREDICTOR_FREE_RUNNING_MAX_STEPS + PREDICTOR_FUTURE_FRAME_COUNT
)
PREDICTOR_TRAINING_FIRST_OFFSET = PREDICTOR_CORE_TRACKER_PREVIOUS_OFFSET
PREDICTOR_TRAINING_SEQUENCE_LENGTH = (
    PREDICTOR_TRAINING_LAST_OFFSET - PREDICTOR_TRAINING_FIRST_OFFSET + 1
)

# DiT 的注意力语义为过去 10 帧、当前 token、Predictor 未来 10 帧。
REALTIME_POSE_CONDITION_WINDOW_LENGTH = PREDICTOR_CORE_TRACKER_CONTEXT_LENGTH
REALTIME_POSE_MODEL_TOKEN_LENGTH = (
    REALTIME_POSE_HISTORY_LENGTH + 1 + PREDICTOR_FUTURE_FRAME_COUNT
)
REALTIME_POSE_FRAME_OFFSETS = (
    *REALTIME_POSE_HISTORY_FRAME_OFFSETS,
    0,
    *tuple(range(1, PREDICTOR_FUTURE_FRAME_COUNT + 1)),
)

# `seq_len` 只保留为训练 CLI 的固定检查项，其语义是 10 帧历史加当前帧。
REALTIME_POSE_SEQ_LEN = REALTIME_POSE_CONDITION_WINDOW_LENGTH

# RPM P2 在 30Hz 下跳过第一秒再统计正式指标；模型仍在历史准备完成后
# 从第 11 帧开始闭环运行，因此第 11～29 帧只用于部署状态预热。
REALTIME_POSE_EVAL_METRICS_START_FRAME = int(REALTIME_POSE_FPS)

# endregion

# region Pose 与 Tracker

SMPL_JOINT_COUNT = 24
ROTATION_6D_DIM = 6
BODY_POSE_DIM = SMPL_JOINT_COUNT * ROTATION_6D_DIM
JOINT_GLOBAL_ROTATION_DIM = BODY_POSE_DIM
REALTIME_POSE_TARGET_DIM = JOINT_GLOBAL_ROTATION_DIM
REALTIME_POSE_INPUT_DIM = REALTIME_POSE_TARGET_DIM

ROOT_DELTA_XZ_DIM = 2
ROOT_HEIGHT_DIM = 1
STATIONARY_PROB_DIM = 5
STATIONARY_JOINT_INDICES = (0, 10, 11, 22, 23)
STATIONARY_JOINT_NAMES = (
    "pelvis",
    "left_foot",
    "right_foot",
    "left_hand",
    "right_hand",
)

TRACKER_COUNT = 6
TRACKER_CONTINUOUS_DIM = 9
TRACKER_FEATURE_DIM = 10
TRACKER_AVAILABLE_OFFSET = 9

TRACKER_NAMES = (
    "head",
    "left_wrist",
    "right_wrist",
    "hip",
    "left_foot",
    "right_foot",
)
HEAD_TRACKER_INDEX = 0
LEFT_HAND_TRACKER_INDEX = 1
RIGHT_HAND_TRACKER_INDEX = 2
HIP_TRACKER_INDEX = 3
LEFT_FOOT_TRACKER_INDEX = 4
RIGHT_FOOT_TRACKER_INDEX = 5
CORE_TRACKER_INDICES = (
    HEAD_TRACKER_INDEX,
    LEFT_HAND_TRACKER_INDEX,
    RIGHT_HAND_TRACKER_INDEX,
)
OPTIONAL_TRACKER_INDICES = (
    HIP_TRACKER_INDEX,
    LEFT_FOOT_TRACKER_INDEX,
    RIGHT_FOOT_TRACKER_INDEX,
)
HAND_TRACKER_INDICES = (LEFT_HAND_TRACKER_INDEX, RIGHT_HAND_TRACKER_INDEX)
FOOT_TRACKER_INDICES = (LEFT_FOOT_TRACKER_INDEX, RIGHT_FOOT_TRACKER_INDEX)
NON_HEAD_TRACKER_INDICES = (1, 2, 3, 4, 5)
NON_HIP_TRACKER_INDICES = (0, 1, 2, 4, 5)
TRACKER_TO_JOINT = (15, 20, 21, 0, 10, 11)

CORE_TRACKER_COUNT = len(CORE_TRACKER_INDICES)
PREDICTOR_TRACKER_ROTATION_DIM = CORE_TRACKER_COUNT * ROTATION_6D_DIM
PREDICTOR_TRACKER_POSITION_DIM = CORE_TRACKER_COUNT * 3
PREDICTOR_SPARSE_DIM = (
    PREDICTOR_TRACKER_ROTATION_DIM * 2 + PREDICTOR_TRACKER_POSITION_DIM * 2
)

CORE_THREE_AVAILABLE = (True, True, True, False, False, False)
ALL_SIX_AVAILABLE = (True, True, True, True, True, True)
TRAIN_TRACKER_ENDPOINTS = (CORE_THREE_AVAILABLE, ALL_SIX_AVAILABLE)
STATIC_OPTIONAL_TRACKER_MASKS = tuple(
    tuple(
        index < 3 or bool(optional_bits[index - 3])
        for index in range(TRACKER_COUNT)
    )
    for optional_bits in (
        (False, False, False),
        (True, False, False),
        (False, True, False),
        (False, False, True),
        (False, True, True),
        (True, True, False),
        (True, False, True),
        (True, True, True),
    )
)

# 当前 Tracker 几何按关节对齐后的模型条件布局保持 10D。
CURRENT_JOINT_CONDITION_DIM = 10
CURRENT_JOINT_TRACKER_POSITION_SLICE = slice(0, 3)
CURRENT_JOINT_TRACKER_POSITION_VALID_INDEX = 3
CURRENT_JOINT_IK_VALID_INDEX = 4
CURRENT_JOINT_IK_CONFIDENCE_INDEX = 5
CURRENT_JOINT_CONSTRAINT_TYPE_START = 6
CURRENT_JOINT_CONSTRAINT_TYPE_COUNT = 4

# endregion


def validate_realtime_seq_len(seq_len: int) -> None:
    if int(seq_len) != REALTIME_POSE_SEQ_LEN:
        raise ValueError(
            f"realtime_pose 固定使用 {REALTIME_POSE_SEQ_LEN} 个条件帧，实际为 {seq_len}"
        )


def validate_realtime_target(target_start: int, target_length: int) -> None:
    if (
        int(target_start) != REALTIME_POSE_TARGET_START
        or int(target_length) != REALTIME_POSE_TARGET_LENGTH
    ):
        raise ValueError("单帧 DiT 固定使用 10 帧历史并只恢复当前帧。")


def validate_tracker_available(available: np.ndarray) -> np.ndarray:
    """校验静态 Tracker 可用性；核心三点在所有样本中必须存在。"""

    values = np.asarray(available, dtype=bool)
    if values.shape[-1] != TRACKER_COUNT:
        raise ValueError(
            f"tracker_available 尾维必须为 {TRACKER_COUNT}，实际为 {values.shape}"
        )
    if not values[..., list(CORE_TRACKER_INDICES)].all():
        raise ValueError("Head、左手和右手 Tracker 必须始终 available。")
    return values
